---
- include_tasks: config.yml

- include_tasks: bootstrap.yml

- include_tasks: start.yml

# We use register as a test to see whether the database is active and ready to
# communicate. This run on all hosts that have a database and attempts to talk
# to the local database rather than the vip,
- include_tasks: register.yml

# This will restart the container we initially used to bootstrap the cluster to
# make it match the other containers environment-wise. This also prevents a
# change from showing up when rerunning the playbooks
- include_tasks: start.yml

# Since the last start.yml may have recreated some containers we must wait and
# check the health again to ensure the hosts are active.
- include_tasks: register.yml

# Test haproxy user through VIP
- include_tasks: check.yml
