---
- include_tasks: register.yml
  when: inventory_hostname in groups['trove-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['trove-api'] or
        inventory_hostname in groups['trove-conductor'] or
        inventory_hostname in groups['trove-taskmanager']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['trove-api']

- include: start.yml
  when: inventory_hostname in groups['trove-api'] or
        inventory_hostname in groups['trove-conductor'] or
        inventory_hostname in groups['trove-taskmanager']
