---
- include_tasks: config.yml

- include_tasks: bootstrap_mons.yml
  when: inventory_hostname in groups['ceph-mon']

- include_tasks: distribute_keyrings.yml

- include_tasks: start_mons.yml
  when: inventory_hostname in groups['ceph-mon']

- include_tasks: bootstrap_osds.yml
  when: inventory_hostname in groups['ceph-osd']

- include_tasks: start_osds.yml
  when: inventory_hostname in groups['ceph-osd']

- include_tasks: start_rgws.yml
  when:
    - enable_ceph_rgw | bool
    - inventory_hostname in groups['ceph-rgw']

- include_tasks: start_rgw_keystone.yml
  when:
    - enable_ceph_rgw_keystone | bool
    - inventory_hostname in groups['ceph-rgw']
