---
- include_tasks: config.yml

- include_tasks: start_mons.yml
  when: inventory_hostname in groups['ceph-mon']

- include_tasks: start_osds.yml
  when: inventory_hostname in groups['ceph-osd']

- include_tasks: start_rgws.yml
  when:
    - enable_ceph_rgw | bool
    - inventory_hostname in groups['ceph-rgw']
