---
- include_tasks: register.yml
  when: inventory_hostname in groups['murano-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['murano-api'] or
        inventory_hostname in groups['murano-engine']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['murano-api']

- include_tasks: start.yml
  when: inventory_hostname in groups['murano-api'] or
        inventory_hostname in groups['murano-engine']
