---
- include_tasks: register.yml
  when: inventory_hostname in groups['ceilometer']

- include_tasks: config.yml
  when: inventory_hostname in groups['ceilometer'] or
        inventory_hostname in groups['compute']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['ceilometer']

- name: Flush handlers
  meta: flush_handlers
