---
- include_tasks: register.yml
  when: enable_keystone | bool and
        (inventory_hostname in groups['ironic-api'] or
        inventory_hostname in groups['ironic-inspector'])

- include_tasks: config.yml

- include_tasks: bootstrap_service.yml

- include_tasks: start.yml
