---
- include_tasks: register.yml
  when: inventory_hostname in groups['watcher-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['watcher-api'] or
        inventory_hostname in groups['watcher-engine'] or
        inventory_hostname in groups['watcher-applier']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['watcher-api']

- name: Flush handlers
  meta: flush_handlers
