---
- include_tasks: register.yml
  when: inventory_hostname in groups['swift-account-server'] or
        inventory_hostname in groups['swift-container-server'] or
        inventory_hostname in groups['swift-object-server'] or
        inventory_hostname in groups['swift-proxy-server']

- include_tasks: disk_and_ring.yml
  when:
    - inventory_hostname in groups['swift-account-server'] or
        inventory_hostname in groups['swift-container-server'] or
        inventory_hostname in groups['swift-object-server'] or
        inventory_hostname in groups['swift-proxy-server']
    - enable_swift_opencontrail | bool

- include_tasks: config.yml
  when: inventory_hostname in groups['swift-account-server'] or
        inventory_hostname in groups['swift-container-server'] or
        inventory_hostname in groups['swift-object-server'] or
        inventory_hostname in groups['swift-proxy-server']

- include_tasks: start.yml
  when: inventory_hostname in groups['swift-account-server'] or
        inventory_hostname in groups['swift-container-server'] or
        inventory_hostname in groups['swift-object-server'] or
        inventory_hostname in groups['swift-proxy-server']

- include_tasks: check.yml
  when: inventory_hostname in groups['swift-account-server'] or
        inventory_hostname in groups['swift-container-server'] or
        inventory_hostname in groups['swift-object-server'] or
        inventory_hostname in groups['swift-proxy-server']
