---
- name: Creating /kolla-cleanup/tools directory on node
  file:
    state: directory
    path: /tmp/kolla-cleanup/tools

- set_fact:
    file_path="{{ "../../../tools" if contrail_cleanup is defined else "../tools" }}"

- debug: msg="{{ file_path }}"

- name: Copying validate-docker-execute.sh file
  copy:
    src: "{{ file_path }}/validate-docker-execute.sh"
    dest: /tmp/kolla-cleanup/tools
    mode: 0755

- name: Copying cleanup-containers file
  copy:
    src: "{{ file_path }}/cleanup-containers"
    dest: /tmp/kolla-cleanup/tools
    mode: 0755

- name: Copying cleanup-host file
  copy:
    src: "{{ file_path }}/cleanup-host"
    dest: /tmp/kolla-cleanup/tools
    mode: 0755

- name: Copying cleanup-images file
  copy:
    src: "{{ file_path }}/cleanup-images"
    dest: /tmp/kolla-cleanup/tools
    mode: 0755
  when:
    - destroy_include_images | bool
